name: ClassicsKotlin

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ClassicsKotlin.yml'
      - 'ClassicsKotlin/**'
  pull_request:
    paths:
      - '.github/workflows/ClassicsKotlin.yml'
      - 'ClassicsKotlin/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-sample-without-check.yml
    with:
      name: ClassicsKotlin
      path: ClassicsKotlin